### ISSUE TITLE
[Help] Any way to use the adapter with my webapp login form ?

### ISSUE THREAD

**Issue by ghost** [ebondu/angular2-keycloak#12]
Is there any way to use the wrapper (keep the refresh tokens management to the adapter) and use my webapp login form to initiate the keycloak login ?
The webapp being the entrypoint of all our services, I want to keep the login context in it, but can't find a way to pass my form params to the adapter and let it manage the auth lifecycle.

**Comment by ebondu** [comment]
Hi,
In the standard OAuth authentication flow, the entrypoint is the keycloak login page. That's why the wrapper build the login page URL from keycloak server URL and then redirect the user to it. After login, the token management is based on OAuth token/codes returned by keycloak server throw the redirect URL. Do you want to customize the login URL to first redirect the user to your webapp login page and then redirect the user to the keycloak from your login page ?

**Comment by ghost** [comment]
This is the flow I would have love (granted it isn't against the RFCs) : 
- Login with username/password in a custom login form
- Use the given credentials to compute the Basic auth tokens
- Rely on the keycloak.json conf to POST a request to the chosen realm
- Handle the response and returned tokens in the keycloak adapter, to continue with the usual flow.

I don't even know if it's allowed, worthy, or in anyway feasible, basically it would be an override of the `Keycloak.login()` method, to manage authentication in my context without having to redirect the user.

**Comment by ebondu** [comment]
It is also possible to grant tokens with the client/secret (Resource Owner Password Credentials Grant) but you can also to use implicit/hybrid flows. Have a look to the [official doc](https://keycloak.gitbooks.io/documentation/content/server_admin/topics/sso-protocols/oidc.html) to find the flow you needs. Then, assuming you retrieved the access token / refresh token / identity (throw your login form + direct grant), you may assign them directly to the corresponding keycloak vars (and also update init/login states subjects if you need authz). Then you can adapt the wrapper to handle a new custom adapter wich will redirect the user to your login form (when refresh tokens are expired) instead of redirecting to keycloak login. Notes that the authorization code flow is the more secured flow, so this approach will be less secured.
Feasible but only by changing the core and adding a new adapter. By using the keycloak login and the wrapper out of the box, you will probably save your time (you will also save time for all other user's managements operations  like password management, registering, external identity providers, etc)...

**Comment by ghost** [comment]
Thanks for your input, this will help with the Costs/Benefits matrix !
I'll be using the standard flow, easy to use and already proven, for the first implementation and we'll see if it's worthy to change it later.
Thanks for your work & dedication !
